name: Tagged Release
on:
  push:
    tags: ['*']

jobs:
  build:
    name: Build and Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Get current tag
      run: echo "CURRENT_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ConsistencyTracker.csproj --configuration Debug -p:version=${{env.CURRENT_TAG}} --no-restore
    - name: Package Mod
      run: zip -q -r ConsistencyTrackerMod.zip everest.yaml bin/ConsistencyTracker.dll bin/ConsistencyTracker.pdb Assets Dialog
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          Tagged release ${{ github.ref_name }}
        draft: true
        prerelease: false
    - name: Upload Mod Asset
      id: upload-mod-release-asset
      uses: actions/upload-release-asset@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ConsistencyTrackerMod.zip
        asset_name: ConsistencyTrackerMod.zip
        asset_content_type: application/zip